language: php
php:
  - '5.5'
  - '5.6'
  - '7.2'
install:
  - composer install
before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction
script:
  - mkdir -p test/output/report
  - composer test
after_script:
  - php vendor/bin/coveralls
